name: NX_CI

on:
  push:
    branches:
      - develop
  release:
    types: [published]
jobs:
  build_NX:
      runs-on: ubuntu-latest
      container: devkitpro/devkita64

      steps:
        # - name: Extract owner and repo
        #   uses: winterjung/split@v2.1.1-rc1
        #   id: repo
        #   with:
        #     seperator: /
        #     msg: ${{ github.repository }}
        - name: Checkout
          uses: actions/checkout@master
          with:
            ref: develop
            submodules: recursive
        - name: Use Docker Build
          uses: actions-hub/docker/cli@master
          env:
              SKIP_LOGIN: true
              
        - run: |
              git config --global --add safe.directory `pwd` && \
              git submodule update --remote && ./build.sh

        - name: Upload file
          uses: actions/upload-artifact@master
          with:
            name: ${{ steps.repo.outputs._1 }} 
            path: dist/
        - uses: actions/download-artifact@master
          with:
            path: sys-clk-action
        - run: |
               find ${{ steps.repo.outputs._1 }}
               cd ${{ steps.repo.outputs._1 }}
               zip -r ${{ steps.repo.outputs._1 }}.zip ${{ steps.repo.outputs._1 }}/ -x "*README.*"
        - name: Upload zip to release
          uses: svenstaro/upload-release-action@master
          with:
            repo_token: ${{ secrets.release_token }}
            file: ./sys-clk-action/*.zip
            tag: ${{ github.ref }}
            file_glob: true
            overwrite: true
